# Generated by Django 5.2.1 on 2025-06-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_createdat_user_created_at_and_more'),
        ('users', '0003_user_auth_provider_user_groups_user_is_active_and_more'),
    ]

    operations = [
    ]
