# Generated by Django 5.2.1 on 2025-06-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emailotp_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastLogin',
            new_name='last_login',
        ),
    ]
