# Generated by Django 5.2.1 on 2025-06-21 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='id',
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.project'),
        ),
    ]
